# UnitsDataArray

UnitsDataArray is the main ouput container for evaluated nodes in PODPAC.
UnitsDataArray is a wrapper around [xarray DataArray](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html)

In [1]:
import numpy as np
from podpac import Node, Coordinates

In [2]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5, 5)
coords = Coordinates([np.linspace(-10, 10, 5), np.linspace(-10, 10, 5)], ['lat', 'lon'])
units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat: 5, lon: 5)>
array([[0.094212, 0.214512, 0.313036, 0.299174, 0.665958],
       [0.109673, 0.465173, 0.653248, 0.755384, 0.718834],
       [0.961505, 0.885992, 0.366108, 0.713193, 0.883381],
       [0.343923, 0.635124, 0.951633, 0.555101, 0.71875 ],
       [0.030709, 0.682862, 0.444499, 0.688995, 0.372793]])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000001EC4B68DCC0>
    units:        None

In [3]:
# get data values
units_data_array.values

# or equivalently
# units_data_array.data

array([[0.09421208, 0.21451178, 0.31303609, 0.29917409, 0.66595812],
       [0.10967306, 0.46517254, 0.65324831, 0.75538382, 0.71883384],
       [0.96150549, 0.88599172, 0.36610752, 0.7131931 , 0.88338075],
       [0.34392339, 0.63512361, 0.95163349, 0.55510127, 0.71874992],
       [0.03070929, 0.68286245, 0.4444994 , 0.68899471, 0.37279334]])

In [4]:
# get data values by coordinate value
units_data_array.loc[-10]

<xarray.UnitsDataArray (lon: 5)>
array([0.094212, 0.214512, 0.313036, 0.299174, 0.665958])
Coordinates:
    lat      float64 -10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000001EC4B68DCC0>
    units:        None

In [5]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [6]:
# get individual xarray coordinates
units_data_array.coords['lat']

# or equivalently:
# units_data_array['lat']

<xarray.UnitsDataArray 'lat' (lat: 5)>
array([-10.,  -5.,   0.,   5.,  10.])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0

In [7]:
# get individual xarray coordinate values
units_data_array.coords['lat'].values

# or equivalently:
# units_data_array.coords['lat'].data
# units_data_array['lat'].values
# units_data_array['lat'].data

array([-10.,  -5.,   0.,   5.,  10.])

In [8]:
# get the dimensions of the DataArray
units_data_array.dims

('lat', 'lon')

### Stacked Coordinates

In [9]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5)
coords = Coordinates([(np.linspace(-10, 10, 5), np.linspace(-10, 10, 5))], ['lat_lon'])

units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat_lon: 5)>
array([0.241324, 0.042525, 0.896666, 0.947253, 0.402767])
Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000001EC4B68DDD8>
    units:        None

In [10]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [11]:
# get the dimensions of the DataArray
units_data_array.dims

('lat_lon',)