# UnitsDataArray

This example shows how to use the UnitsDataArray object:

* UnitsDataArray is the main ouput container for evaluated nodes in PODPAC.
* UnitsDataArray is a wrapper around [xarray DataArray](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html)


1. The first section shows the basic usage, which is similar to xarray.DataArray
2. The second section shows the added functionality which includes units

In [1]:
import numpy as np
from podpac import Node, Coordinates

D:\podpac-1.1.0\miniconda\envs\podpac\lib\site-packages\xarray\core\merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)


## Basic Functionality

In [2]:
# create an empty node, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5, 5)
coords = Coordinates([np.linspace(-10, 10, 5), np.linspace(-10, 10, 5)], ['lat', 'lon'])
units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat: 5, lon: 5)>
array([[0.535428, 0.966141, 0.555205, 0.921753, 0.472046],
       [0.221715, 0.121907, 0.062524, 0.730363, 0.699582],
       [0.114342, 0.979162, 0.102736, 0.546111, 0.384572],
       [0.498139, 0.071765, 0.827767, 0.716282, 0.320969],
       [0.429473, 0.906439, 0.864659, 0.227773, 0.34254 ]])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x0000012C7CF04668>
    crs:          EPSG:4326

In [3]:
# get data values
units_data_array.values

# or equivalently
# units_data_array.data

array([[0.53542818, 0.96614136, 0.55520491, 0.92175344, 0.47204647],
       [0.22171461, 0.12190729, 0.06252387, 0.73036312, 0.69958191],
       [0.11434186, 0.97916162, 0.10273561, 0.54611066, 0.38457191],
       [0.4981387 , 0.07176483, 0.82776716, 0.71628184, 0.32096948],
       [0.42947317, 0.90643874, 0.86465939, 0.22777318, 0.34253967]])

In [4]:
# get data values by coordinate value
units_data_array.loc[-10]

<xarray.UnitsDataArray (lon: 5)>
array([0.535428, 0.966141, 0.555205, 0.921753, 0.472046])
Coordinates:
    lat      float64 -10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x0000012C7CF04668>
    crs:          EPSG:4326

In [5]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [6]:
# get individual xarray coordinates
units_data_array.coords['lat']

# or equivalently:
# units_data_array['lat']

<xarray.UnitsDataArray 'lat' (lat: 5)>
array([-10.,  -5.,   0.,   5.,  10.])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0

In [7]:
# get individual xarray coordinate values
units_data_array.coords['lat'].values

# or equivalently:
# units_data_array.coords['lat'].data
# units_data_array['lat'].values
# units_data_array['lat'].data

array([-10.,  -5.,   0.,   5.,  10.])

In [8]:
# get the dimensions of the DataArray
units_data_array.dims

('lat', 'lon')

### Stacked Coordinates

In [9]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5)
coords = Coordinates([(np.linspace(-10, 10, 5), np.linspace(-10, 10, 5))], ['lat_lon'])

units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat_lon: 5)>
array([0.683888, 0.390376, 0.609361, 0.686888, 0.63761 ])
Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x0000012C7CF04630>
    crs:          EPSG:4326

In [10]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [11]:
# get the dimensions of the DataArray
units_data_array.dims

('lat_lon',)

## Added Functionality (Units)

In [12]:
# Create Nodes to use the convience methods for making units data arrays
kgs_node = Node(units='kg')
lbs_node = Node(units='lbs')
data = np.ones(1)
coords = Coordinates([0], ['alt'])

# Create units data arrays, each for meters and feet
kgs = kgs_node.create_output_array(coords, data=data)
lbs = lbs_node.create_output_array(coords, data=data)
print (kgs, '\n------------\n', lbs)

<xarray.UnitsDataArray (alt: 1)>
array([1.])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x0000012C7CEFE278>
    crs:          EPSG:4326
    units:        kilogram 
------------
 <xarray.UnitsDataArray (alt: 1)>
array([1.])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x0000012C7CEFEDA0>
    crs:          EPSG:4326
    units:        pound


In [13]:
kgs + lbs

<xarray.UnitsDataArray (alt: 1)>
array([1.453592])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    units:    kilogram

In [14]:
# Note, order is important: the result here is in pounds instead of kilograms as above
lbs + kgs

<xarray.UnitsDataArray (alt: 1)>
array([3.204623])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    units:    pound

In [15]:
# We can convert between the units
lbs.to('kg')

<xarray.UnitsDataArray (alt: 1)>
array([0.453592])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    units:    kg

In [16]:
# Incorrect units results in an error
try: 
    lbs ** 2 + kgs
except Exception as e: 
    print(e)

Cannot convert from 'kilogram' ([mass]) to 'pound ** 2' ([mass] ** 2)


In [17]:
# Unless your settings are such that unit checking is not enabled
import podpac
podpac.settings["ENABLE_UNITS"] = False
print (lbs **2 + kgs)
podpac.settings["ENABLE_UNITS"] = True

<xarray.UnitsDataArray (alt: 1)>
array([2.])
Coordinates:
  * alt      (alt) float64 0.0


In [18]:
# Units are also preserved over statistical operations
kgs.min()

<xarray.UnitsDataArray ()>
array(1.)
Attributes:
    units:    kilogram