# UnitsDataArray

This example shows how to use the UnitsDataArray object:

* UnitsDataArray is the main ouput container for evaluated nodes in PODPAC.
* UnitsDataArray is a wrapper around [xarray DataArray](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html)


1. The first section shows the basic usage, which is similar to xarray.DataArray
2. The second section shows the added functionality which includes units

In [1]:
import numpy as np
from podpac import Node, Coordinates

## Basic Functionality

In [2]:
# create an empty node, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5, 5)
coords = Coordinates([np.linspace(-10, 10, 5), np.linspace(-10, 10, 5)], ['lat', 'lon'])
units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat: 5, lon: 5)>
array([[0.06593 , 0.727046, 0.58315 , 0.348207, 0.218971],
       [0.699058, 0.415367, 0.041533, 0.183593, 0.658694],
       [0.895681, 0.373953, 0.664759, 0.410672, 0.522258],
       [0.417362, 0.687666, 0.05125 , 0.409815, 0.998319],
       [0.175771, 0.597347, 0.570972, 0.883967, 0.109599]])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x00000217313C76A0>
    crs:          EPSG:4326

In [3]:
# get data values
units_data_array.values

# or equivalently
# units_data_array.data

array([[0.06592974, 0.72704623, 0.58315047, 0.34820719, 0.21897057],
       [0.69905807, 0.41536675, 0.04153298, 0.18359331, 0.65869357],
       [0.8956807 , 0.37395328, 0.66475943, 0.41067156, 0.52225774],
       [0.41736176, 0.6876664 , 0.05125015, 0.40981476, 0.99831898],
       [0.1757709 , 0.5973468 , 0.57097168, 0.88396713, 0.10959941]])

In [4]:
# get data values by coordinate value
units_data_array.loc[-10]

<xarray.UnitsDataArray (lon: 5)>
array([0.06593 , 0.727046, 0.58315 , 0.348207, 0.218971])
Coordinates:
    lat      float64 -10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x00000217313C76A0>
    crs:          EPSG:4326

In [5]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [6]:
# get individual xarray coordinates
units_data_array.coords['lat']

# or equivalently:
# units_data_array['lat']

<xarray.UnitsDataArray 'lat' (lat: 5)>
array([-10.,  -5.,   0.,   5.,  10.])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0

In [7]:
# get individual xarray coordinate values
units_data_array.coords['lat'].values

# or equivalently:
# units_data_array.coords['lat'].data
# units_data_array['lat'].values
# units_data_array['lat'].data

array([-10.,  -5.,   0.,   5.,  10.])

In [8]:
# get the dimensions of the DataArray
units_data_array.dims

('lat', 'lon')

### Stacked Coordinates

In [9]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5)
coords = Coordinates([(np.linspace(-10, 10, 5), np.linspace(-10, 10, 5))], ['lat_lon'])

units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat_lon: 5)>
array([0.737009, 0.639034, 0.407546, 0.548552, 0.720742])
Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x00000217313C77B8>
    crs:          EPSG:4326

In [10]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [11]:
# get the dimensions of the DataArray
units_data_array.dims

('lat_lon',)

## Added Functionality (Units)

In [39]:
# Create Nodes to use the convience methods for making units data arrays
kgs_node = Node(units='kg')
lbs_node = Node(units='lbs')
data = np.ones(1)
coords = Coordinates([0], ['alt'])

# Create units data arrays, each for meters and feet
kgs = kgs_node.create_output_array(coords, data=data)
lbs = lbs_node.create_output_array(coords, data=data)
print (kgs, '\n------------\n', lbs)

<xarray.UnitsDataArray (alt: 1)>
array([1.])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x00000217316386A0>
    crs:          EPSG:4326
    units:        kilogram 
------------
 <xarray.UnitsDataArray (alt: 1)>
array([1.])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x0000021731638E80>
    crs:          EPSG:4326
    units:        pound


In [15]:
kgs + lbs

<xarray.UnitsDataArray (alt: 1)>
array([1.453592])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    units:    kilogram

In [16]:
# Note, order is important: the result here is in pounds instead of kilograms as above
lbs + kgs

<xarray.UnitsDataArray (alt: 1)>
array([3.204623])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    units:    pound

In [17]:
# We can convert between the units
lbs.to('kg')

<xarray.UnitsDataArray (alt: 1)>
array([0.453592])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    units:    kg

In [22]:
# Incorrect units results in an error
try: 
    lbs ** 2 + kgs
except Exception as e: 
    print(e)

Cannot convert from 'kilogram' ([mass]) to 'pound ** 2' ([mass] ** 2)


In [25]:
# Unless your settings are such that unit checking is not enabled
import podpac
podpac.settings["ENABLE_UNITS"] = False
print (lbs **2 + kgs)
podpac.settings["ENABLE_UNITS"] = True

<xarray.UnitsDataArray (alt: 1)>
array([2.])
Coordinates:
  * alt      (alt) float64 0.0


In [35]:
# Units are also preserved over statistical operations
kgs.min()

<xarray.UnitsDataArray ()>
array(1.)
Attributes:
    units:    kilogram