# UnitsDataArray

This example shows how to use the UnitsDataArray object:

* UnitsDataArray is the main ouput container for evaluated nodes in PODPAC.
* UnitsDataArray is a wrapper around [xarray DataArray](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html)


1. The first section shows the basic usage, which is similar to xarray.DataArray
2. The second section shows the added functionality which includes units

In [1]:
import numpy as np
from podpac import Node, Coordinates

D:\podpac-1.2.0\miniconda\envs\podpac\lib\site-packages\xarray\core\merge.py:17: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  PANDAS_TYPES = (pd.Series, pd.DataFrame, pd.Panel)


## Basic Functionality

In [2]:
# create an empty node, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5, 5)
coords = Coordinates([np.linspace(-10, 10, 5), np.linspace(-10, 10, 5)], ['lat', 'lon'])
units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat: 5, lon: 5)>
array([[0.603929, 0.385354, 0.994428, 0.177364, 0.080804],
       [0.620498, 0.7148  , 0.507009, 0.695481, 0.693377],
       [0.39615 , 0.418461, 0.112567, 0.950012, 0.339331],
       [0.923082, 0.945241, 0.38231 , 0.56567 , 0.736953],
       [0.679023, 0.676336, 0.951489, 0.384004, 0.384986]])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000002A9B62799E8>
    crs:          EPSG:4326

In [3]:
# get data values
units_data_array.values

# or equivalently
# units_data_array.data

array([[0.60392915, 0.38535429, 0.99442752, 0.17736415, 0.08080438],
       [0.62049765, 0.71479983, 0.50700866, 0.69548122, 0.6933771 ],
       [0.39615022, 0.41846096, 0.11256729, 0.95001176, 0.33933126],
       [0.92308194, 0.94524145, 0.3823105 , 0.56566985, 0.73695327],
       [0.67902286, 0.67633646, 0.95148879, 0.38400422, 0.38498626]])

In [4]:
# get data values by coordinate value
units_data_array.loc[-10]

<xarray.UnitsDataArray (lon: 5)>
array([0.603929, 0.385354, 0.994428, 0.177364, 0.080804])
Coordinates:
    lat      float64 -10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000002A9B62799E8>
    crs:          EPSG:4326

In [5]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [6]:
# get individual xarray coordinates
units_data_array.coords['lat']

# or equivalently:
# units_data_array['lat']

<xarray.UnitsDataArray 'lat' (lat: 5)>
array([-10.,  -5.,   0.,   5.,  10.])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0

In [7]:
# get individual xarray coordinate values
units_data_array.coords['lat'].values

# or equivalently:
# units_data_array.coords['lat'].data
# units_data_array['lat'].values
# units_data_array['lat'].data

array([-10.,  -5.,   0.,   5.,  10.])

In [8]:
# get the dimensions of the DataArray
units_data_array.dims

('lat', 'lon')

### Stacked Coordinates

In [9]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5)
coords = Coordinates([(np.linspace(-10, 10, 5), np.linspace(-10, 10, 5))], ['lat_lon'])

units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat_lon: 5)>
array([0.154293, 0.499825, 0.324625, 0.838053, 0.849685])
Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000002A9B62BAFD0>
    crs:          EPSG:4326

In [10]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [11]:
# get the dimensions of the DataArray
units_data_array.dims

('lat_lon',)

## Added Functionality (Units)

In [12]:
# Create Nodes to use the convience methods for making units data arrays
kgs_node = Node(units='kg')
lbs_node = Node(units='lbs')
data = np.ones(1)
coords = Coordinates([0], ['alt'])

# Create units data arrays, each for meters and feet
kgs = kgs_node.create_output_array(coords, data=data)
lbs = lbs_node.create_output_array(coords, data=data)
print (kgs, '\n------------\n', lbs)

<xarray.UnitsDataArray (alt: 1)>
array([1.])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000002A9B62BA4E0>
    crs:          EPSG:4326
    units:        kilogram 
------------
 <xarray.UnitsDataArray (alt: 1)>
array([1.])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000002A9B6279A20>
    crs:          EPSG:4326
    units:        pound


In [13]:
kgs + lbs

<xarray.UnitsDataArray (alt: 1)>
array([1.453592])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    units:    kilogram

In [14]:
# Note, order is important: the result here is in pounds instead of kilograms as above
lbs + kgs

<xarray.UnitsDataArray (alt: 1)>
array([3.204623])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    units:    pound

In [15]:
# We can convert between the units
lbs.to('kg')

<xarray.UnitsDataArray (alt: 1)>
array([0.453592])
Coordinates:
  * alt      (alt) float64 0.0
Attributes:
    units:    kg

In [16]:
# Incorrect units results in an error
try: 
    lbs ** 2 + kgs
except Exception as e: 
    print(e)

Cannot convert from 'kilogram' ([mass]) to 'pound ** 2' ([mass] ** 2)


In [17]:
# Unless your settings are such that unit checking is not enabled
import podpac
podpac.settings["ENABLE_UNITS"] = False
print (lbs **2 + kgs)
podpac.settings["ENABLE_UNITS"] = True

<xarray.UnitsDataArray (alt: 1)>
array([2.])
Coordinates:
  * alt      (alt) float64 0.0


In [18]:
# Units are also preserved over statistical operations
kgs.min()

<xarray.UnitsDataArray ()>
array(1.)
Attributes:
    units:    kilogram