In [9]:
from podpac.datalib import nexrad
from podpac import Coordinates, crange, clinspace
import nexradaws
import numpy as np
from datetime import datetime

import warnings
warnings.filterwarnings('ignore')

%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


## Get Available Radars


In [5]:
coords = Coordinates([crange('2018-01-02 01:33:11', '2018-01-04 06:43:21', '1,D')], dims=['time'])
radars = nexrad.get_radars(coords)

radars

['KFDR',
 'KPBZ',
 'KLVX',
 'KMHX',
 'KMQT',
 'KEAX',
 'KCXX',
 'KCLE',
 'KJAX',
 'KMKX',
 'KMLB',
 'KMRX',
 'KLBB',
 'KDVN',
 'KLOT',
 'KBOX',
 'KHGX',
 'KCAE',
 'KHNX',
 'KEPZ',
 'KTLX',
 'KCLX',
 'PAPD',
 'KMPX',
 'KPAH',
 'KFDX',
 'KBIS',
 'KAPX',
 'KLRX',
 'KPUX',
 'KRAX',
 'KVBX',
 'RKJK',
 'KDIX',
 'KFCX',
 'PHWA',
 'KBUF',
 'KHTX',
 'KAKQ',
 'KOAX',
 'KDLH',
 'KDTX',
 'KHPX',
 'KIWX',
 'KMUX',
 'KAMA',
 'KJGX',
 'FOP1',
 'PAKC',
 'KATX',
 'KBHX',
 'KVAX',
 'KUEX',
 'KEOX',
 'KENX',
 'KEMX',
 'KLGX',
 'KVTX',
 'KSOX',
 'KGRR',
 'KHDX',
 'RODN',
 'KAMX',
 'KCCX',
 'KTWX',
 'KFWS',
 'KMBX',
 'KMOB',
 'KTBW',
 'KTYX',
 'KDAX',
 'KDGX',
 'KBLX',
 'KMXX',
 'KGRB',
 'KABX',
 'KVNX',
 'KMVX',
 'KABR',
 'KDMX',
 'KLIX',
 'KMTX',
 'KMAF',
 'KILN',
 'KLZK',
 'KIND',
 'KGGW',
 'KLNX',
 'KRGX',
 'KSRX',
 'KTFX',
 'KNQA',
 'KRIW',
 'RKSG',
 'KBMX',
 'KPDT',
 'KGWX',
 'KPOE',
 'KFFC',
 'KILX',
 'KTLH',
 'KDFX',
 'KDOX',
 'KICT',
 'KARX',
 'KOHX',
 'KFSD',
 'KEWX',
 'KMAX',
 'KCBW',
 'KESX',
 

## Nexrad DataSource

In [2]:
node = nexrad.NexradSource(source='KABR20100101_001550_V03.gz')

In [3]:
node.native_coordinates

2010/01/01/KABR/KABR20100101_001550_V03.gz


/Users/marcus/computing/python/anaconda3/envs/podpac2/lib/python3.6/site-packages/pyart/io/nexrad_archive.py:207: UserWarning: Gate spacing is not constant, interpolating data in scans [4, 5, 6] for moment REF.
  UserWarning)


Coordinates
	lat_lon[lat]: ArrayCoordinates1d(lat): Bounds[41.326177935269186, 49.58548834082003], N[7254720], ctype['midpoint']
	lat_lon[lon]: ArrayCoordinates1d(lon): Bounds[-104.30536019212853, -92.52020199539581], N[7254720], ctype['midpoint']
	time: ArrayCoordinates1d(time): Bounds[2010-01-01T00:15:50.000000, 2010-01-01T00:15:50.000000], N[1], ctype['midpoint']

In [3]:
c = Coordinates([clinspace(42, 44, 3), clinspace(-98, -100, 3), ['2010-01-01T00:15:50.000000']], dims=['lat', 'lon', 'time'])

In [3]:
data = node.get_data('', '')
data

2010/01/01/KABR/KABR20100101_001550_V03.gz


array([-3.e+00, -8.e+00, -2.e+01, ...,  1.e+20,  1.e+20,  1.e+20],
      dtype=float32)

In [11]:
lat = node.radar.gate_latitude['data']
lon = node.radar.gate_longitude['data']

# figure()
plot(lon.ravel(), lat.ravel(), marker='.')
# show()

In [4]:
data = node.eval(c)
data

2010/01/01/KABR/KABR20100101_001550_V03.gz


/Users/marcus/computing/python/anaconda3/envs/podpac2/lib/python3.6/site-packages/pyart/io/nexrad_archive.py:207: UserWarning: Gate spacing is not constant, interpolating data in scans [4, 5, 6] for moment REF.
  UserWarning)
/Users/marcus/computing/python/anaconda3/envs/podpac2/lib/python3.6/site-packages/traitlets/traitlets.py:567: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  silent = bool(old_value == new_value)
/Users/marcus/computing/python/anaconda3/envs/podpac2/lib/python3.6/site-packages/traitlets/traitlets.py:567: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  silent = bool(old_value == new_value)
/Users/marcus/computing/python/anaconda3/envs/podpac2/lib/python3.6/site-packages/traitlets/traitlet

<xarray.UnitsDataArray (lat: 3, lon: 3, time: 1)>
array([[[nan],
        [nan],
        [nan]],

       [[nan],
        [nan],
        [nan]],

       [[nan],
        [nan],
        [nan]]])
Coordinates:
  * lat      (lat) float64 42.0 43.0 44.0
  * lon      (lon) float64 -98.0 -99.0 -100.0
  * time     (time) datetime64[us] 2010-01-01T00:15:50
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x1c1ad2b518>
    units:        None

In [27]:
len(np.hstack(data.filled()))

7254720

In [5]:
node.native_coordinates['lat']

ArrayCoordinates1d(lat): Bounds[41.326177935269186, 49.58548834082003], N[7254720], ctype['midpoint']

In [35]:
node.radar.gate_latitude['data']

array([[45.45972001, 45.46017684, 45.46063359, ..., 46.14817179,
        46.14846634, 46.14876074],
       [45.45956204, 45.46000028, 45.46043845, ..., 46.1137061 ,
        46.11398178, 46.11425734],
       [45.45938758, 45.4598053 , 45.46022294, ..., 46.07565647,
        46.07591131, 46.07616616],
       ...,
       [45.45138569, 45.45086203, 45.4503383 , ..., 44.36248998,
        44.36182632, 44.36116217],
       [45.45106138, 45.45049957, 45.44993769, ..., 44.29414917,
        44.29344942, 44.29274915],
       [45.45073502, 45.45013482, 45.44953455, ..., 44.22545614,
        44.22472015, 44.22398362]])

In [39]:
node.radar.ngates

1832

In [8]:
node = nexrad.Nexrad()

In [11]:
c = nexrad._s3.meta.client.list_objects(Bucket='noaa-nexrad-level2', Prefix='2010/01')
c

{'ResponseMetadata': {'RequestId': 'E326DA3A8D7512B7',
  'HostId': 'XmjcQM/aT3VpPLSZZNf6UT1Oa30CFy68iWKe/OrdJxlnDYp8aUhpL27R2ot1Z3Ce3CdmWUCX22o=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'XmjcQM/aT3VpPLSZZNf6UT1Oa30CFy68iWKe/OrdJxlnDYp8aUhpL27R2ot1Z3Ce3CdmWUCX22o=',
   'x-amz-request-id': 'E326DA3A8D7512B7',
   'date': 'Thu, 06 Dec 2018 01:27:34 GMT',
   'x-amz-bucket-region': 'us-east-1',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'IsTruncated': True,
 'Marker': '',
 'Contents': [{'Key': '2010/01/01/KABR/KABR20100101_000618_V03.gz',
   'LastModified': datetime.datetime(2017, 12, 20, 13, 40, 49, tzinfo=tzutc()),
   'ETag': '"aa48174b4d7cc159461c1b97e86f398b"',
   'Size': 282032,
   'StorageClass': 'STANDARD',
   'Owner': {'DisplayName': 'aws-pds-noaa-bdp-nexrad',
    'ID': '7f4603da1c74099579f30c0cb95d12b2762dfe960ccac8db42e709402a325a6d'}},
  {'Key': '2010/01/01/KABR/KABR20100101_001550_V0

In [49]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[7,8,9], [14,15,16]])

(np.hstack(a), np.hstack(b))

(array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 14, 15, 16]))

# Using Nexradpy

In [24]:
import matplotlib.pyplot as plt
import pytz
from datetime import datetime
import pyart

templocation = './nexrad'

import nexradaws
conn = nexradaws.NexradAwsInterface()

conn.get_available_radars


Downloaded KDVN20170731_002402_V06
Downloaded KDVN20170731_000509_V06
Downloaded KDVN20170731_003328_V06
Downloaded KDVN20170731_001435_V06
4 out of 4 files downloaded...0 errors


In [ ]:
availscans = conn.get_avail_scans('2017', '07', '31', 'KDVN')
results = conn.download(availscans[0:4], templocation)

In [25]:
for i,scan in enumerate(results.iter_success(),start=1):
    radar = scan.open_pyart()
    print(radar.latitude)
    print(radar.longitude)

{'long_name': 'Latitude', 'standard_name': 'Latitude', 'units': 'degrees_north', 'data': array([41.61166763])}
{'long_name': 'Longitude', 'standard_name': 'Longitude', 'units': 'degrees_east', 'data': array([-90.58083344])}
{'long_name': 'Latitude', 'standard_name': 'Latitude', 'units': 'degrees_north', 'data': array([41.61166763])}
{'long_name': 'Longitude', 'standard_name': 'Longitude', 'units': 'degrees_east', 'data': array([-90.58083344])}
{'long_name': 'Latitude', 'standard_name': 'Latitude', 'units': 'degrees_north', 'data': array([41.61166763])}
{'long_name': 'Longitude', 'standard_name': 'Longitude', 'units': 'degrees_east', 'data': array([-90.58083344])}
{'long_name': 'Latitude', 'standard_name': 'Latitude', 'units': 'degrees_north', 'data': array([41.61166763])}
{'long_name': 'Longitude', 'standard_name': 'Longitude', 'units': 'degrees_east', 'data': array([-90.58083344])}


In [23]:

for i,scan in enumerate(results.iter_success(),start=1):
    radar = scan.open_pyart()
    print(radar.latitude)
    print(radar.longitude)

{'long_name': 'Latitude', 'standard_name': 'Latitude', 'units': 'degrees_north', 'data': array([41.61166763])}
{'long_name': 'Longitude', 'standard_name': 'Longitude', 'units': 'degrees_east', 'data': array([-90.58083344])}
{'long_name': 'Latitude', 'standard_name': 'Latitude', 'units': 'degrees_north', 'data': array([41.61166763])}
{'long_name': 'Longitude', 'standard_name': 'Longitude', 'units': 'degrees_east', 'data': array([-90.58083344])}
{'long_name': 'Latitude', 'standard_name': 'Latitude', 'units': 'degrees_north', 'data': array([41.61166763])}
{'long_name': 'Longitude', 'standard_name': 'Longitude', 'units': 'degrees_east', 'data': array([-90.58083344])}
{'long_name': 'Latitude', 'standard_name': 'Latitude', 'units': 'degrees_north', 'data': array([41.61166763])}
{'long_name': 'Longitude', 'standard_name': 'Longitude', 'units': 'degrees_east', 'data': array([-90.58083344])}


In [40]:
radar.gate_latitude['data']

array([[41.61374663, 41.61399085, 41.61423499, ..., 41.92963397,
        41.92973467, 41.92983529],
       [41.61391228, 41.61417599, 41.61443962, ..., 41.96555375,
        41.965674  , 41.96579415],
       [41.61407685, 41.61435992, 41.61464291, ..., 42.00124551,
        42.00138515, 42.00152474],
       ...,
       [41.62189683, 41.62309997, 41.62430306, ..., 43.71484232,
        43.71592438, 43.71700706],
       [41.62218031, 41.62341681, 41.62465325, ..., 43.77787526,
        43.7789925 , 43.78011039],
       [41.62246348, 41.62373331, 41.62500307, ..., 43.8409084 ,
        43.84206086, 43.843214  ]])

In [16]:
radar.fields['reflectivity']['data']

NameError: name 'radar' is not defined

In [43]:
radar.fields

{'cross_correlation_ratio': {'units': 'ratio',
  'standard_name': 'cross_correlation_ratio_hv',
  'long_name': 'Cross correlation_ratio (RHOHV)',
  'valid_max': 1.0,
  'valid_min': 0.0,
  'coordinates': 'elevation azimuth range',
  '_FillValue': -9999.0,
  'data': masked_array(
    data=[[0.9183333516120911, 0.9516666531562805, 0.9049999713897705, ...,
           --, --, --],
          [0.9783333539962769, --, --, ..., --, --, --],
          [0.9883333444595337, --, --, ..., --, --, --],
          ...,
          [0.7616666555404663, 0.7549999952316284, 0.8116666674613953, ...,
           --, --, --],
          [0.9183333516120911, 0.8516666889190674, 0.4350000023841858, ...,
           --, --, --],
          [0.9649999737739563, 0.9616666436195374, 0.9516666531562805, ...,
           --, --, --]],
    mask=[[False, False, False, ...,  True,  True,  True],
          [False,  True,  True, ...,  True,  True,  True],
          [False,  True,  True, ...,  True,  True,  True],
          ...,

In [29]:
fig = plt.figure(figsize=(16,12))
for i,scan in enumerate(results.iter_success(),start=1):
    ax = fig.add_subplot(2,2,i)
    radar = scan.open_pyart()
    display = pyart.graph.RadarDisplay(radar)
    display.plot('reflectivity',0,ax=ax,title="{} {}".format(scan.radar_id,scan.scan_time))
    display.set_limits((-150, 150), (-150, 150), ax=ax)

{'long_name': 'Longitude',
 'standard_name': 'Longitude',
 'units': 'degrees_east',
 'data': array([-90.58083344])}

# Pyart


In [26]:
from pyart.io.nexrad_common import NEXRAD_LOCATIONS

In [47]:
NEXRAD_LOCATIONS

{'KABR': {'lat': 45.45583, 'lon': -98.41306, 'elev': 1302},
 'KABX': {'lat': 35.14972, 'lon': -106.82333, 'elev': 5870},
 'KAKQ': {'lat': 36.98389, 'lon': -77.0075, 'elev': 112},
 'KAMA': {'lat': 35.23333, 'lon': -101.70889, 'elev': 3587},
 'KAMX': {'lat': 25.61056, 'lon': -80.41306, 'elev': 14},
 'KAPX': {'lat': 44.90722, 'lon': -84.71972, 'elev': 1464},
 'KARX': {'lat': 43.82278, 'lon': -91.19111, 'elev': 1276},
 'KATX': {'lat': 48.19472, 'lon': -122.49444, 'elev': 494},
 'KBBX': {'lat': 39.49611, 'lon': -121.63167, 'elev': 173},
 'KBGM': {'lat': 42.19972, 'lon': -75.985, 'elev': 1606},
 'KBHX': {'lat': 40.49833, 'lon': -124.29194, 'elev': 2402},
 'KBIS': {'lat': 46.77083, 'lon': -100.76028, 'elev': 1658},
 'KBLX': {'lat': 45.85389, 'lon': -108.60611, 'elev': 3598},
 'KBMX': {'lat': 33.17194, 'lon': -86.76972, 'elev': 645},
 'KBOX': {'lat': 41.95583, 'lon': -71.1375, 'elev': 118},
 'KBRO': {'lat': 25.91556, 'lon': -97.41861, 'elev': 23},
 'KBUF': {'lat': 42.94861, 'lon': -78.73694, '

In [49]:
import re
_radar_re = re.compile(r'^\d{4}/\d{2}/\d{2}/(....)/')

In [61]:
_radar_re.search('2018/02/12/PCG/').group(1)

AttributeError: 'NoneType' object has no attribute 'group'

In [62]:
[_radar_re.match(entry).group(1) for entry in ['2018/02/12/PCG/', '2018/02/12/PCDG/'] \
                                if _radar_re.match(entry) is not None]

['PCDG']

In [64]:
set([1,2]) | set([1])

{1, 2}