In [ ]:
import warnings
warnings.filterwarnings('ignore')

## SMAP Data Acess via EGI Interface

SMAP Data is Available via the [EGI Interface](https://developer.earthdata.nasa.gov/sdps/programmatic-access-docs). The `podpac.datalib.egi.EGI` DataSource node provides access to the EGI Interface. The `podpac.datalib.smap_egi.SMAP` DataSource node wraps the EGI interface with SMAP specific handling.

## Provide Earth Data Login Credentials

If you do not have an earth data login, or have not activated OpenDAP access, follow the [instructions here](https://creare-com.github.io/podpac-docs/user/earthdata.html)

In [2]:
import getpass
username = password = None
username = input("Username:");   password = getpass.getpass('Password:')

Username: mls_creare
Password: ························


## SMAP Access

In [3]:
from podpac.datalib.smap_egi import SMAP, SMAP_PRODUCTS
from podpac import Coordinates, clinspace

INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials


### List Products

In [4]:
# list all available SMAP products
SMAP_PRODUCTS

['SPL4SMAU',
 'SPL4SMGP',
 'SPL4SMLM',
 'SPL3SMAP',
 'SPL3SMA',
 'SPL3SMP_AM',
 'SPL3SMP_PM',
 'SPL3SMP_E_AM',
 'SPL3SMP_E_PM']

### Level 3 Access

In [5]:
# coordinates to investigate
c = Coordinates([clinspace(-82, -81, 10), clinspace(38, 39, 10), clinspace('2015-07-06', '2015-07-08', 10)], dims=['lon', 'lat', 'time'])

In [6]:
# podpac node
node = SMAP(product="SPL3SMP_AM", username=username, password=password)
output = node.eval(c)
output

<xarray.UnitsDataArray (lon: 10, lat: 10, time: 10)>
array([[[0.329151, 0.329151, ..., 0.363082, 0.363082],
        [0.329151, 0.329151, ..., 0.363082, 0.363082],
        ...,
        [0.361225, 0.361225, ..., 0.323132, 0.323132],
        [0.361225, 0.361225, ..., 0.323132, 0.323132]],

       [[0.329151, 0.329151, ..., 0.363082, 0.363082],
        [0.329151, 0.329151, ..., 0.363082, 0.363082],
        ...,
        [0.361225, 0.361225, ..., 0.323132, 0.323132],
        [0.361225, 0.361225, ..., 0.323132, 0.323132]],

       ...,

       [[0.409944, 0.409944, ..., 0.408964, 0.408964],
        [0.409944, 0.409944, ..., 0.408964, 0.408964],
        ...,
        [0.36381 , 0.36381 , ..., 0.352789, 0.352789],
        [0.36381 , 0.36381 , ..., 0.352789, 0.352789]],

       [[0.409944, 0.409944, ..., 0.408964, 0.408964],
        [0.409944, 0.409944, ..., 0.408964, 0.408964],
        ...,
        [0.36381 , 0.36381 , ..., 0.352789, 0.352789],
        [0.36381 , 0.36381 , ..., 0.352789, 0.35278

In [7]:
node = SMAP(product="SPL3SMA", username=username, password=password)
output = node.eval(c)
output

<xarray.UnitsDataArray (lon: 10, lat: 10, time: 10)>
array([[[     nan,      nan, ...,      nan,      nan],
        [0.322736, 0.322736, ...,      nan,      nan],
        ...,
        [0.222105, 0.222105, ...,      nan,      nan],
        [     nan,      nan, ...,      nan,      nan]],

       [[     nan,      nan, ...,      nan,      nan],
        [0.532599, 0.532599, ...,      nan,      nan],
        ...,
        [0.227933, 0.227933, ...,      nan,      nan],
        [     nan,      nan, ...,      nan,      nan]],

       ...,

       [[     nan,      nan, ...,      nan,      nan],
        [     nan,      nan, ...,      nan,      nan],
        ...,
        [     nan,      nan, ...,      nan,      nan],
        [     nan,      nan, ...,      nan,      nan]],

       [[     nan,      nan, ..., 0.535665, 0.535665],
        [0.337784, 0.337784, ...,      nan,      nan],
        ...,
        [0.554143, 0.554143, ...,      nan,      nan],
        [0.381876, 0.381876, ...,      nan,      na

### Level 4 Access

In [8]:
# coordinates to investigate
c = Coordinates([clinspace(-82, -81, 10), clinspace(38, 39, 10), clinspace('2015-07-06', '2015-07-08', 10)], dims=['lon', 'lat', 'time'])

In [9]:
# podpac node
node = SMAP(product="SPL4SMAU", username=username, password=password)
output = node.eval(c)
output

/Users/marcus/computing/creare/podpac/podpac/podpac/core/coordinates/dependent_coordinates.py:491: UserWarning: transformation of coordinate segment lengths not yet implemented
  warnings.warn("transformation of coordinate segment lengths not yet implemented")
/Users/marcus/computing/creare/podpac/podpac/podpac/core/coordinates/dependent_coordinates.py:493: UserWarning: transformation of coordinate segment lengths not yet implemented
  warnings.warn("transformation of coordinate segment lengths not yet implemented")


<xarray.UnitsDataArray (lon: 10, lat: 10, time: 10)>
array([[[nan, nan, ..., nan, nan],
        [nan, nan, ..., nan, nan],
        ...,
        [nan, nan, ..., nan, nan],
        [nan, nan, ..., nan, nan]],

       [[nan, nan, ..., nan, nan],
        [nan, nan, ..., nan, nan],
        ...,
        [nan, nan, ..., nan, nan],
        [nan, nan, ..., nan, nan]],

       ...,

       [[nan, nan, ..., nan, nan],
        [nan, nan, ..., nan, nan],
        ...,
        [nan, nan, ..., nan, nan],
        [nan, nan, ..., nan, nan]],

       [[nan, nan, ..., nan, nan],
        [nan, nan, ..., nan, nan],
        ...,
        [nan, nan, ..., nan, nan],
        [nan, nan, ..., nan, nan]]])
Coordinates:
  * lon      (lon) float64 -82.0 -81.89 -81.78 -81.67 ... -81.22 -81.11 -81.0
  * lat      (lat) float64 38.0 38.11 38.22 38.33 ... 38.67 38.78 38.89 39.0
  * time     (time) datetime64[ns] 2015-07-06 2015-07-06T05:20:00 ... 2015-07-08
Attributes:
    layer_style:  <podpac.core.style.Style object at 

In [10]:
node.data

<xarray.UnitsDataArray (time: 10, lat: 11, lon: 11)>
array([[[0.217252, 0.30324 , ..., 0.235802, 0.238751],
        [0.218393, 0.302374, ..., 0.240443, 0.244053],
        ...,
        [0.257682, 0.259882, ..., 0.275255, 0.280957],
        [0.26754 , 0.228202, ..., 0.275878, 0.282042]],

       [[0.216478, 0.303017, ..., 0.234787, 0.238225],
        [0.217708, 0.302064, ..., 0.239156, 0.242906],
        ...,
        [0.344133, 0.348837, ..., 0.278268, 0.283159],
        [0.347869, 0.331462, ..., 0.278827, 0.283946]],

       ...,

       [[0.218441, 0.307128, ..., 0.251241, 0.250555],
        [0.219922, 0.305321, ..., 0.253055, 0.252517],
        ...,
        [0.274226, 0.27552 , ..., 0.271702, 0.277276],
        [0.281802, 0.240512, ..., 0.269979, 0.275501]],

       [[0.217231, 0.305804, ..., 0.250755, 0.253467],
        [0.218176, 0.303581, ..., 0.251867, 0.25469 ],
        ...,
        [0.272703, 0.273811, ..., 0.269426, 0.2754  ],
        [0.279844, 0.238416, ..., 0.267905, 0.27397

In [19]:
## Debug lat/lon values
c = node.native_coordinates
c.transform('epsg:4326')

/Users/marcus/computing/creare/podpac/podpac/podpac/core/coordinates/dependent_coordinates.py:491: UserWarning: transformation of coordinate segment lengths not yet implemented
  warnings.warn("transformation of coordinate segment lengths not yet implemented")
/Users/marcus/computing/creare/podpac/podpac/podpac/core/coordinates/dependent_coordinates.py:493: UserWarning: transformation of coordinate segment lengths not yet implemented
  warnings.warn("transformation of coordinate segment lengths not yet implemented")
/anaconda3/envs/podpac/lib/python3.7/site-packages/numpy/core/fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


Coordinates (epsg:4326)
	time: ArrayCoordinates1d(time): Bounds[2015-07-05T13:00:00.000000000, 2015-07-06T16:00:00.000000000], N[10], ctype['point']
	lat,lon[lat]: DependentCoordinates(i,j->lat): Bounds[nan, nan], shape(11, 11), ctype[midpoint]
	lat,lon[lon]: DependentCoordinates(i,j->lon): Bounds[46.820542, 47.754152], shape(11, 11), ctype[midpoint]