# UnitsDataArray

*Author: Creare* <br>
*Date: April 01 2020* <br>

**Keywords**: podpac, UnitsDataArray

## Overview

Reference tutorial for the `podpac.UnitsDataArray` class.

### Prerequisites

- Python 2.7 or above
- [`podpac`](https://podpac.org/install.html#install)
- *Review the [README.md](../README.md) and [jupyter-tutorial.ipynb](jupyter-tutorial.ipynb) for additional info on using jupyter notebooks*

### See Also

- [introduction.ipynb](introduction.ipynb): PODPAC introduction
- `podpac.UnitsDataArray` API Reference - In Development
- [xarray](xarray.ipynb): Short reference for the core [`xarray`](https://xarray.pydata.org/en/stable/) module.

## Background

This example shows how to use the UnitsDataArray object:

* `UnitsDataArray` is the main ouput container for evaluated nodes in PODPAC.
* UnitsDataArray is a thin wrapper around [xarray DataArray](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html)


1. The first section shows the basic usage, which is similar to `xarray.DataArray`
2. The second section shows the added functionality which includes units

## Basic Functionality

In [1]:
import podpac
import numpy as np

# create an empty node
node = podpac.Node()

# create randome 5 x 5 matrix of data
data = np.random.rand(5, 5)

# create mock Coordinates describing the location of each data point
coords = podpac.Coordinates([np.linspace(-10, 10, 5), np.linspace(-10, 10, 5)], ['lat', 'lon'])

# Use the convience method `Node.create_output_array` to create a `UnitsDataArray`
units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat: 5, lon: 5)>
array([[0.334902, 0.641183, 0.789909, 0.170834, 0.468675],
       [0.451214, 0.035324, 0.446735, 0.254254, 0.678561],
       [0.021265, 0.743173, 0.371617, 0.158077, 0.903146],
       [0.195654, 0.750435, 0.229103, 0.41883 , 0.272802],
       [0.610927, 0.073832, 0.171876, 0.49935 , 0.991305]])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000001F7FFD7DE80>
    crs:          EPSG:4326

In [2]:
# get data values
units_data_array.values

# or equivalently
units_data_array.data

array([[0.33490193, 0.64118339, 0.78990864, 0.17083394, 0.46867485],
       [0.45121433, 0.03532357, 0.44673546, 0.25425418, 0.67856144],
       [0.02126482, 0.74317323, 0.37161664, 0.15807677, 0.90314608],
       [0.19565396, 0.75043463, 0.22910258, 0.41883048, 0.2728016 ],
       [0.61092652, 0.07383181, 0.17187644, 0.49935036, 0.99130525]])

In [3]:
# get data values by coordinate value
units_data_array.loc[-10]

<xarray.UnitsDataArray (lon: 5)>
array([0.334902, 0.641183, 0.789909, 0.170834, 0.468675])
Coordinates:
    lat      float64 -10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000001F7FFD7DE80>
    crs:          EPSG:4326

In [4]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [5]:
# get individual xarray coordinates
units_data_array.coords['lat']

# or equivalently:
# units_data_array['lat']

<xarray.UnitsDataArray 'lat' (lat: 5)>
array([-10.,  -5.,   0.,   5.,  10.])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0

In [6]:
# get individual xarray coordinate values
units_data_array.coords['lat'].values

# or equivalently:
# units_data_array.coords['lat'].data
# units_data_array['lat'].values
# units_data_array['lat'].data

array([-10.,  -5.,   0.,   5.,  10.])

In [7]:
# get the dimensions of the DataArray
units_data_array.dims

('lat', 'lon')

### Stacked Coordinates

In [8]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = podpac.Node()
data = np.random.rand(5)
coords = podpac.Coordinates([(np.linspace(-10, 10, 5), np.linspace(-10, 10, 5))], ['lat_lon'])

units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat_lon: 5)>
array([0.885157, 0.440241, 0.587473, 0.018747, 0.505369])
Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000001F7852A20B8>
    crs:          EPSG:4326

In [9]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [10]:
# get the dimensions of the DataArray
units_data_array.dims

('lat_lon',)

## Added Functionality (Units)

In [11]:
# Create Nodes to use the convience methods for making units data arrays
kgs_node = podpac.Node(units='kg')
lbs_node = podpac.Node(units='lbs')
data = np.ones(1)
coords = podpac.Coordinates([0], ['lat'])

In [12]:
# create UnitsDataArray for kg
kgs = kgs_node.create_output_array(coords, data=data)
kgs

<xarray.UnitsDataArray (lat: 1)>
array([1.])
Coordinates:
  * lat      (lat) float64 0.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000001F785A3B358>
    crs:          EPSG:4326
    units:        kilogram

In [13]:
# create UnitsDataArray for lbs
lbs = lbs_node.create_output_array(coords, data=data)
lbs

<xarray.UnitsDataArray (lat: 1)>
array([1.])
Coordinates:
  * lat      (lat) float64 0.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000001F7FFD7DCF8>
    crs:          EPSG:4326
    units:        pound

In [14]:
kgs + lbs

<xarray.UnitsDataArray (lat: 1)>
array([1.453592])
Coordinates:
  * lat      (lat) float64 0.0
Attributes:
    units:    kilogram

In [15]:
# Note, order is important: the result here is in pounds instead of kilograms as above
lbs + kgs

<xarray.UnitsDataArray (lat: 1)>
array([3.204623])
Coordinates:
  * lat      (lat) float64 0.0
Attributes:
    units:    pound

In [16]:
# We can convert between the units
lbs.to('kg')

<xarray.UnitsDataArray (lat: 1)>
array([0.453592])
Coordinates:
  * lat      (lat) float64 0.0
Attributes:
    units:    kg

In [17]:
# Incorrect units results in an error
try: 
    lbs ** 2 + kgs
except Exception as e: 
    print(e)

Cannot convert from 'kilogram' ([mass]) to 'pound ** 2' ([mass] ** 2)


In [18]:
# Unless your settings are such that unit checking is not enabled
from podpac import settings

settings["ENABLE_UNITS"] = False

print (lbs **2 + kgs)
settings["ENABLE_UNITS"] = True

<xarray.UnitsDataArray (lat: 1)>
array([2.])
Coordinates:
  * lat      (lat) float64 0.0


In [19]:
# Units are also preserved over statistical operations
kgs.min()

<xarray.UnitsDataArray ()>
array(1.)
Attributes:
    units:    kilogram