# UnitsDataArray

This example shows how to use the UnitsDataArray object:

* `UnitsDataArray` is the main ouput container for evaluated nodes in PODPAC.
* UnitsDataArray is a thin wrapper around [xarray DataArray](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.html)


1. The first section shows the basic usage, which is similar to xarray.DataArray
2. The second section shows the added functionality which includes units

In [1]:
import podpac
import numpy as np

## Basic Functionality

In [2]:
# create an empty node
node = podpac.Node()

# create randome 5 x 5 matrix of data
data = np.random.rand(5, 5)

# create mock Coordinates describing the location of each data point
coords = podpac.Coordinates([np.linspace(-10, 10, 5), np.linspace(-10, 10, 5)], ['lat', 'lon'])

# Use the convience method `Node.create_output_array` to create a `UnitsDataArray`
units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat: 5, lon: 5)>
array([[0.643709, 0.905504, 0.353818, 0.008807, 0.49075 ],
       [0.494664, 0.319305, 0.193745, 0.065925, 0.698598],
       [0.882936, 0.891336, 0.982282, 0.026203, 0.479   ],
       [0.754011, 0.013454, 0.51558 , 0.041264, 0.890437],
       [0.878071, 0.18996 , 0.457569, 0.906961, 0.729032]])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x0000023F693F3DA0>
    crs:          EPSG:4326

In [3]:
# get data values
units_data_array.values

# or equivalently
units_data_array.data

array([[0.64370914, 0.90550367, 0.35381805, 0.00880661, 0.49074977],
       [0.49466428, 0.31930506, 0.19374488, 0.06592546, 0.69859793],
       [0.88293569, 0.89133633, 0.98228152, 0.02620341, 0.47899998],
       [0.75401073, 0.01345384, 0.51557981, 0.04126356, 0.89043714],
       [0.87807124, 0.18996012, 0.45756925, 0.90696106, 0.72903174]])

In [4]:
# get data values by coordinate value
units_data_array.loc[-10]

<xarray.UnitsDataArray (lon: 5)>
array([0.89218815, 0.71263837, 0.54655294, 0.5175978 , 0.9255926 ])
Coordinates:
    lat      float64 -10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000002552D39B388>
    crs:          EPSG:4326

In [5]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0
  * lon      (lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [6]:
# get individual xarray coordinates
units_data_array.coords['lat']

# or equivalently:
# units_data_array['lat']

<xarray.UnitsDataArray 'lat' (lat: 5)>
array([-10.,  -5.,   0.,   5.,  10.])
Coordinates:
  * lat      (lat) float64 -10.0 -5.0 0.0 5.0 10.0

In [7]:
# get individual xarray coordinate values
units_data_array.coords['lat'].values

# or equivalently:
# units_data_array.coords['lat'].data
# units_data_array['lat'].values
# units_data_array['lat'].data

array([-10.,  -5.,   0.,   5.,  10.])

In [8]:
# get the dimensions of the DataArray
units_data_array.dims

('lat', 'lon')

### Stacked Coordinates

In [9]:
# create an empty note, then use the convience method `create_output_array` to create
# an output array with data at specific Coordinates
node = Node()
data = np.random.rand(5)
coords = Coordinates([(np.linspace(-10, 10, 5), np.linspace(-10, 10, 5))], ['lat_lon'])

units_data_array = node.create_output_array(coords, data=data)

units_data_array

<xarray.UnitsDataArray (lat_lon: 5)>
array([0.05186409, 0.46529885, 0.61387435, 0.55846114, 0.29083946])
Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000002552D3D9588>
    crs:          EPSG:4326

In [10]:
# get xarray coordinates
print(type(units_data_array.coords))
units_data_array.coords

<class 'xarray.core.coordinates.DataArrayCoordinates'>


Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0
  - lon      (lat_lon) float64 -10.0 -5.0 0.0 5.0 10.0

In [11]:
# get the dimensions of the DataArray
units_data_array.dims

('lat_lon',)

## Added Functionality (Units)

In [13]:
# Create Nodes to use the convience methods for making units data arrays
kgs_node = Node(units='kg')
lbs_node = Node(units='lbs')
data = np.ones(1)
coords = Coordinates([0], ['lat'])

# Create units data arrays, each for meters and feet
kgs = kgs_node.create_output_array(coords, data=data)
lbs = lbs_node.create_output_array(coords, data=data)
print (kgs, '\n------------\n', lbs)

<xarray.UnitsDataArray (lat: 1)>
array([1.])
Coordinates:
  * lat      (lat) float64 0.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000002552D39B108>
    crs:          EPSG:4326
    units:        kilogram 
------------
 <xarray.UnitsDataArray (lat: 1)>
array([1.])
Coordinates:
  * lat      (lat) float64 0.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x000002552D39B1C8>
    crs:          EPSG:4326
    units:        pound


In [14]:
kgs + lbs

<xarray.UnitsDataArray (lat: 1)>
array([1.45359237])
Coordinates:
  * lat      (lat) float64 0.0
Attributes:
    units:    kilogram

In [15]:
# Note, order is important: the result here is in pounds instead of kilograms as above
lbs + kgs

<xarray.UnitsDataArray (lat: 1)>
array([3.20462262])
Coordinates:
  * lat      (lat) float64 0.0
Attributes:
    units:    pound

In [16]:
# We can convert between the units
lbs.to('kg')

<xarray.UnitsDataArray (lat: 1)>
array([0.45359237])
Coordinates:
  * lat      (lat) float64 0.0
Attributes:
    units:    kg

In [17]:
# Incorrect units results in an error
try: 
    lbs ** 2 + kgs
except Exception as e: 
    print(e)

Cannot convert from 'kilogram' ([mass]) to 'pound ** 2' ([mass] ** 2)


In [18]:
# Unless your settings are such that unit checking is not enabled
import podpac
podpac.settings["ENABLE_UNITS"] = False
print (lbs **2 + kgs)
podpac.settings["ENABLE_UNITS"] = True

<xarray.UnitsDataArray (lat: 1)>
array([2.])
Coordinates:
  * lat      (lat) float64 0.0


In [19]:
# Units are also preserved over statistical operations
kgs.min()

<xarray.UnitsDataArray ()>
array(1.)
Attributes:
    units:    kilogram