# Jupyter Tutorial For PODPAC

*Author: Creare* <br>
*Date: April 01 2020* <br>

**Keywords**: Jupyter, JupyterLab, Notebooks

## Overview

Short tutorial for using Jupyter Notebooks with PODPAC.

### Prerequisites

- Python 2.7 or above
- [`podpac[notebook]`](https://podpac.org/install.html#install)

### See Also

- Official [JupyterLab Documentation](https://jupyterlab.readthedocs.io/en/stable/user/interface.html)
- **Help** menu in the JupyterLab menu bar

## Launch JupyterLab

- Browse to the location of the `podpac-examples` repository (or other directory to launch JupyterLab)
- Launch a JupyterLab session

```
$ jupyter lab
```

## Using JupyterLab

To launch an example notebook:

* Browse to an example using the file-browser on the left panel
* Double-click the file 
* From the top menu, select `Run --> Run All`

<img src='../images/JupyterHowTo.gif' width='80%' />

## Keyboard Shortcuts

There are multiple useful keyboard shortcuts, as shown below. For example, for evaluating cells in the notebook:
* `Ctrl-Enter`: Evaluate current cell
* `Shift-Enter`: Evaluate current cell and select the next cell
* `Alt-Enter`: Evaluate current cell and create a new cell after it

<img src='../images/notebook-keyboard-shortcuts.jpg' width='50%' />

## Plotting

To display static plots in the notebook, run the following [IPython magic](http://ipython.readthedocs.io/en/stable/interactive/tutorial.html#magics-explained) commands in the notebook before plotting:

In [1]:
# simple static plots
%matplotlib inline

For interactive plots, use the [ipympl](https://github.com/matplotlib/ipympl) widget.

This requires an extra step during installation to include the `jupyter-matplotlib` extension. You must restart JupyterLab after installing the extension:

```
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib
```

Run the following [IPython magic](http://ipython.readthedocs.io/en/stable/interactive/tutorial.html#magics-explained) commands in the notebook before plotting to load the `ipympl` backend.

In [2]:
# interactive plots - requires `ipympl` extension
%matplotlib widget

Often you will the command `pass` at the end of a cell that outputs a plot.
This prevents `.plot()` from displaying outputs

In [3]:
import matplotlib.pyplot as plt

plt.plot()
# you will see plot handle [] output

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[]

In [4]:
import matplotlib.pyplot as plt

plt.plot()
pass  # suppresses output

## Ignore Warnings

Some packages may display warnings in the Jupyter interface everytime they are loaded.

To ignore these warnings, use the following code snippet at the top of your notebook:

In [5]:
import warnings
warnings.filterwarnings("ignore")

## View Help and Docstrings 

Use `?` before a module or function to see the docstring

In [6]:
import datetime

? datetime

Type:        module
String form: <module 'datetime' from 'C:\\Anaconda3\\envs\\podpac\\lib\\datetime.py'>
File:        c:\anaconda3\envs\podpac\lib\datetime.py
Docstring:   Fast implementation of the datetime type.


In [7]:
import numpy as np

? np.ones

Signature:  np.ones(shape, dtype=None, order='C')
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and order.

See Also
--------
ones_like : Return an array of ones with shape and type of input.
empty : Return a new uninitialized array.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.


Examples
--------
>>> np.ones(5)
array([1., 1., 1., 1., 1.])

>>> np.ones((5,), dtype=int)
array([1, 1, 1, 1, 1])

>>> np.ones((2, 1))
array([[1.],
   

## Viewing Markdown in JupterLab

To make a Markdown (.md) file (i.e. [README.md](../README.md))  more readable in JupyterLab:

* Right-click the text editor
* Select `Show Markdown Preview`

A new window will open and show a nicely rendered version of the file.