# Creating a MATLAB-like environment in Python

*Author: Creare* <br>
*Date: April 01 2020* <br>

**Keywords**: Python, MATLAB

## Overview

Short tutorial to help experienced MATLAB users get started with Python.

### Prerequisites

- Python 2.7 or above
- [`numpy`](https://www.numpy.org/), [`matplotlib`](https://matplotlib.org/)
- *Review the [README.md](../README.md) and [jupyter-tutorial.ipynb](jupyter-tutorial.ipynb) for additional info on using jupyter notebooks*


### See Also

- [basic-reference.ipynb](basic-reference.ipynb): Basic introduction to Python language features
- [Numpy for MATLAB users](https://docs.scipy.org/doc/numpy-1.15.0/user/numpy-for-matlab-users.html) is a useful reference for new users.

## Importing modules

* Unlike MATLAB, Python libraries need to be `imported` before they can be used
* Imported libraries usually have a namespace
* Portions of libraries, can be imported

In [2]:
import os  # miscellaneous operating system interfaces
import sys # system-specific parameters and functions
import datetime # basic date and time types

# only import the `timedelta` function from `datetime`
from datetime import timedelta

# import `numpy` library as `np` 
import numpy as np

## View module contents

Use the `dir` command to see the contents of a module:

In [10]:
# see
dir(datetime)

['MAXYEAR',
 'MINYEAR',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'date',
 'datetime',
 'datetime_CAPI',
 'time',
 'timedelta',
 'timezone',
 'tzinfo']

Anything that starts with the *dunderscore* `__<attr>__` is an internal Python method and can be ignored. 

## View docstring

In the Jupyter interface, use `?` before any module or function to see the docstring:

In [8]:
import numpy as np

? np.ones

Signature: np.ones(shape, dtype=None, order='C')
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and order.

See Also
--------
ones_like : Return an array of ones with shape and type of input.
empty : Return a new uninitialized array.
zeros : Return a new array setting values to zero.
full : Return a new array of given shape filled with value.


Examples
--------
>>> np.ones(5)
array([ 1.,  1.,  1.,  1.,  1.])

>>> np.ones((5,), dtype=int)
array([1, 1, 1, 1, 1])

>>> np.ones((2, 1))
array([[ 1.]

## Creating a MATLAB-like environment in Python

> [**NumPy**](https://www.numpy.org/) and [**Matplotlib**](https://matplotlib.org/) libraries

Unlike MATLAB, the standard Python library does not come with array-handling and plotting capabilities. 

* For array-handling, the `numpy` Python package can be used, and is generally imported as follows:

In [11]:
import numpy as np

* For plotting, the `Matplotlib` Python package can be used, and is generally imported as follows:

In [12]:
import matplotlib.pyplot as plt

* `Matplotlib` plotting routines use nearly the same interface as MATLAB plotting routines.
* Both `Numpy` and `Matplotlib` can be imported as follows:

In [13]:
from matplotlib.pylab import *

## IPython Magic Functions

When using JupyterLab or an IPython console, the [IPython magic function](https://ipython.org/ipython-doc/dev/interactive/magics.html) `%pylab` can be used.

In [14]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


This magic function, when invoked, can be instructed to use different plotting "Backends", and that affects how plots are displayed

```python 
%pylab  # nothing specified will default to creating a new window for plots
%pylab inline  # this will create images (non-interactive) inside the console or JupyterLab notebook
%pylab ipympl  # thiw will create interactive plots inside JupyterLab notebooks
```